import { StyleSheet } from "react-native";
import colors from "../../../../colors";
import normalize from "react-native-normalize";

const ChangeStatusGroupStyles = StyleSheet.create({
  GroupListContainer: {
    display: "flex",
    flexDirection: "column",
    width: 390,
    height: 150,
    paddingBottom: 2,
    boxSizing: "border-box",
    alignItems: "center",
    marginTop: 20,
    //borderRadius: 40,
    padding: 20,
    left: 15,
  },

  GroupListContainerBG: {
    position: "absolute",
    width: 390,
    height: 150,
    left: -5,
  },
  GroupListContainerHeader: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    height: 25,
    boxSizing: "border-box",
    //backgroundColor: "red",
    alignItems: "center",
    justifyContent: "space-between",
  },
  GroupNameText: {
    color: "rgba(79,69,124,1)",
    fontSize: 20,
    lineHeight: 20,
    //fontFamily: "Inter, sans-serif",
    fontWeight: "700",
    alignItems: "center",
    textAlignVertical: "center",
  },
  ExcludeMembersContainer: {
    display: "flex",
    flexDirection: "row",
    height: "100%",
    width: "37%",
    justifyContent: "space-between",
  },

  MaterialSymbolsPersonRemoveRounded: {
    textAlignVertical: "center",
    top: 3,
    width: 18,
    height: 18,
  },
  ExcludeMembers: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    height: "100%",
    color: "rgba(56,49,87,1)",
    fontSize: 12,
    lineHeight: 12,
    //fontFamily: "Inter, sans-serif",
    fontWeight: "400",
    textAlign: "center",
    textAlignVertical: "center",
  },

  GroupList: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    height: 95,
    boxSizing: "border-box",
    //backgroundColor: "blue"
  },

  OneGroup: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    margin: 5,
    boxSizing: "border-box",
    marginBottom: 20,
    width: 60,
  },
  Portrait: {
    width: 55,
    height: 55,
  },

  Member: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    color: "rgba(122,107,188,1)",
    fontSize: 10,
    lineHeight: 10,
    fontWeight: "500",
    textAlign: "center",
    marginTop: 10,
    width: "100%",
  },

  HomeDefaultStatusInvisible: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    width: "100%",
    paddingTop: 46,
    boxSizing: "border-box",
    backgroundColor: "rgba(246,246,255,1)",
    height: "100%",
    //backgroundColor: "rgba(246,1,1,1)"
  },

  TopHalf: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    boxSizing: "border-box",
    //backgroundColor: "rgba(246,1,1,1)",
  },
  Header: {
    display: "flex",
    flexDirection: "row",
    boxSizing: "border-box",
    justifyContent: "space-between",
    width: "100%",
    //backgroundColor: "rgba(246,1,1,1)",
    paddingHorizontal: 20,
    marginTop: 10,
    alignItems: "center",
  },
  BackArrowIcon: {
    width: 24,
    height: 24,
  },
  HeaderPageText: {
    color: "rgba(0,0,0,1)",
    fontSize: 16,
    lineHeight: 25,
    left: -80,
    //fontFamily: "Inter, sans-serif",
    fontWeight: "700",
    justifyContent: "center",
  },
  SaveButton: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    height: "100%",
    borderRadius: 50,
    boxSizing: "border-box",
    backgroundColor: "rgba(122,107,188,1)",
  },
  SaveHeaderButtonBG: {
    display: "flex",
    flexDirection: "column",

    justifyContent: "flex-start",
    alignItems: "flex-start",
    width: "100%",
    paddingLeft: 19,
    paddingRight: 19,
    paddingTop: 8,
    paddingBottom: 11,
    borderRadius: 30,
    boxSizing: "border-box",
    backgroundColor: "rgba(122,107,188,1)",
  },
  SaveText: {
    top: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    color: "rgba(255,255,255,1)",
    fontSize: 16,
    lineHeight: 16,
    //fontFamily: "Inter, sans-serif",
    fontWeight: "700",
    textAlign: "center",
  },

  BottomHalf: {
    position: "absolute",
    top: 300,
    display: "flex",
    flexDirection: "column",
    width: "100%",
    height: 805,
    paddingLeft: 36,
    paddingRight: 100,
    paddingTop: 25,
    borderRadius: 50,
    paddingBottom: 664,
    boxSizing: "border-box",
    backgroundColor: "rgba(255,255,255,1)",
  },
  SetYourDefaultStatusText: {
    color: "rgba(79,69,124,1)",
    fontSize: 20,
    lineHeight: 20,
    //fontFamily: "Inter, sans-serif",
    fontWeight: "800",
    width: "120%",
  },
  SetYourDefaultStatusDesc: {
    color: "rgba(104,104,104,1)",
    fontSize: 13,
    lineHeight: 13,
    //fontFamily: "Inter, sans-serif",
    fontWeight: "400",
    marginTop: 8,
  },
  DefaultStatus2: {
    color: "rgba(79,69,124,1)",
    fontSize: 20,
    lineHeight: 20,
    //fontFamily: "Inter, sans-serif",
    fontWeight: "700",
    marginTop: 40,
  },
  Osilist: {
    width: 312,
    height: 148,
    boxSizing: "border-box",
    //backgroundColor: "rgba(246,1,1,1)",
    marginTop: 10,
  },

  OptionsStatusIndicatorSelected: {
    backgroundColor: "rgba(217,217,217,0.5)",
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: "25%",
    paddingLeft: 8,
    paddingRight: 11,
    paddingTop: 6,
    paddingBottom: 5,
    borderRadius: 10,
    boxSizing: "border-box",
  },
  StatusIndicator: {
    width: 26,
    height: "100%",
  },
  OSIText: {
    color: "rgba(79,69,124,1)",
    fontSize: 14,
    lineHeight: 14,
    //fontFamily: "Inter, sans-serif",
    fontWeight: "500",
    textAlign: "left",
    width: "75%",
  },
  RadioButton: {
    width: 19,
    height: 19,
  },
  OptionsStatusIndicator: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: "25%",
    paddingLeft: 8,
    paddingRight: 11,
    paddingTop: 6,
    paddingBottom: 5,
    boxSizing: "border-box",
    //backgroundColor: "black"
  },

  SetStatusMessageGroup: {
    width: 309,
    height: 67,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    boxSizing: "border-box",
    marginTop: 30,
  },

  SetStatusMessageGroupHeader: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    width: "100%",
    boxSizing: "border-box",
  },
  SetStatusMessageText: {
    marginBottom: 2,
    color: "rgba(90,80,132,1)",
    fontSize: 15,
    lineHeight: 15,
    //fontFamily: "Inter, sans-serif",
    fontWeight: "700",
    width: "70%",
  },
  OptionalText: {
    color: "rgba(100,100,100,1)",
    fontSize: 10,
    lineHeight: 10,
    //fontFamily: "Inter, sans-serif",
    fontWeight: "400",
    textAlign: "right",
    width: "30%",
  },
  SetStatusMessageTextBox: {
    width: "100%",
    height: 42,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,1)",
    borderRadius: 5,
    boxSizing: "border-box",
    padding: 10,
  },

  ClearAfterHeader: {
    marginTop: 30,
    display: "flex",
    flexDirection: "column",
    width: "100%",
    boxSizing: "border-box",
  },

  ClearAfterDesc: {
    marginTop: 5,
    color: "rgba(100,100,100,1)",
    fontSize: 11,
    lineHeight: 12,
    //fontFamily: "Inter, sans-serif",
    fontWeight: "400",
    textAlign: "left",
    width: "100%",
  },

  dropdown1BtnStyle: {
    top: 20,
    width: "100%",
    height: 50,
    backgroundColor: "#FFF",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#444",
    fontSize: 20,
  },
  dropdown1BtnTxtStyle: { color: "#444", textAlign: "left" },
  dropdown1DropdownStyle: { backgroundColor: "#EFEFEF" },
  dropdown1RowStyle: {
    backgroundColor: "#EFEFEF",
    borderBottomColor: "#C5C5C5",
  },
  dropdown1RowTxtStyle: { color: "#444", textAlign: "left" },
});

export default ChangeStatusGroupStyles;
